# =============================================================================
# HexShield AI — JSON Forensic Report Generator
# Layer 3: Forensic Preservation and Reporting Module
#
# Generates machine-readable JSON forensic reports.
# JSON reports are used for:
#   - SIEM integration
#   - Inter-agency data sharing
#   - Automated processing pipelines
#   - Archive and long-term storage
# =============================================================================

import json
import logging
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Tuple

from app.services.forensic_reporting.report_generator import (
    ForensicReportData,
    compute_report_hash,
    ensure_report_filepath,
    determine_overall_verdict,
)

logger = logging.getLogger(__name__)


class JSONReportGenerator:
    """
    Generates machine-readable JSON forensic reports.
    """

    REPORT_VERSION = "1.0.0"

    def generate(
        self, report_data: ForensicReportData
    ) -> Tuple[bytes, str, str]:
        """
        Generate a JSON forensic report.

        Args:
            report_data: Assembled ForensicReportData object

        Returns:
            Tuple of (report_bytes, report_filename, report_hash)
        """
        logger.info(
            f"Generating JSON report for submission "
            f"{report_data.submission.id}"
        )

        overall_verdict = determine_overall_verdict(
            hex_risk=report_data.hex_analysis.overall_risk_level
            if report_data.hex_analysis else None,
            ai_verdict=report_data.ai_analysis.verdict
            if report_data.ai_analysis else None,
        )

        report_dict = {
            "report_metadata": {
                "report_id": report_data.report_id,
                "report_version": self.REPORT_VERSION,
                "report_type": report_data.report_type,
                "report_format": "JSON",
                "generated_at": report_data.generated_at,
                "issuing_authority": report_data.issuing_authority,
                "jurisdiction": report_data.jurisdiction,
                "overall_forensic_verdict": overall_verdict,
            },
            "case_information": {
                "case_id": report_data.case.id,
                "case_reference": report_data.case.case_reference,
                "case_title": report_data.case.case_title,
                "classification": report_data.case.classification,
                "jurisdiction": report_data.case.jurisdiction,
                "applicable_law": report_data.case.applicable_law,
                "lead_investigator": {
                    "name": report_data.case.lead_investigator.full_name,
                    "badge": report_data.case.lead_investigator.badge_number,
                    "organization": report_data.case.lead_investigator.organization,
                    "role": report_data.case.lead_investigator.role,
                },
            },
            "evidence_record": {
                "submission_id": report_data.submission.id,
                "original_filename": report_data.submission.original_filename,
                "file_size_bytes": report_data.submission.file_size_bytes,
                "ingestion_timestamp": report_data.submission.ingestion_timestamp,
                "submitted_by": {
                    "name": report_data.submission.submitted_by.full_name,
                    "badge": report_data.submission.submitted_by.badge_number,
                    "organization": report_data.submission.submitted_by.organization,
                },
                "cryptographic_integrity": {
                    "sha256_hash": report_data.submission.sha256_hash,
                    "sha512_hash": report_data.submission.sha512_hash,
                    "hash_algorithm_primary": "SHA-256",
                    "hash_algorithm_secondary": "SHA-512",
                },
                "mime_type_declared": report_data.submission.mime_type_declared,
                "mime_type_detected": report_data.submission.mime_type_detected,
            },
            "layer_1_hex_triage": self._build_hex_section(
                report_data.hex_analysis
            ),
            "layer_2_ai_analysis": self._build_ai_section(
                report_data.ai_analysis
            ),
            "chain_of_custody": self._build_custody_section(
                report_data.custody_chain
            ),
            "examiner_notes": report_data.examiner_notes,
            "additional_findings": report_data.additional_findings,
            "legal_disclaimer": (
                "This report was generated by HexShield AI, a digital forensic "
                "analysis platform. The findings contained herein are based on "
                "automated analysis and should be reviewed by a qualified forensic "
                "examiner before presentation in legal proceedings. Hash values "
                "provided constitute the cryptographic integrity baseline for the "
                "analyzed evidence under ISO/IEC 27037 standards."
            ),
        }

        # Serialize to formatted JSON
        report_bytes = json.dumps(
            report_dict, indent=2, ensure_ascii=False, default=str
        ).encode("utf-8")

        # Generate filename
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        case_ref = report_data.case.case_reference.replace("-", "_")
        report_filename = (
            f"HEXSHIELD_{case_ref}_{report_data.submission.id[:8]}"
            f"_{timestamp}_FORENSIC_REPORT.json"
        )

        # Compute report hash
        report_hash = compute_report_hash(report_bytes)

        # Save to disk with automatic nested directory building
        report_path = ensure_report_filepath(report_filename)
        report_path.write_bytes(report_bytes)

        logger.info(
            f"JSON report generated: {report_filename} "
            f"({len(report_bytes)} bytes), hash={report_hash[:16]}..."
        )

        return report_bytes, report_filename, report_hash

    # -------------------------------------------------------------------------
    # PRIVATE — Section Builders
    # -------------------------------------------------------------------------

    def _build_hex_section(self, hex_data) -> dict:
        if not hex_data:
            return {"status": "NOT_PERFORMED"}
        return {
            "status": "COMPLETED",
            "analysis_id": hex_data.analysis_id,
            "analyzed_at": hex_data.analyzed_at,
            "engine_version": hex_data.engine_version,
            "findings": {
                "overall_risk_level": hex_data.overall_risk_level,
                "risk_summary": hex_data.risk_summary,
                "shannon_entropy": {
                    "value": hex_data.shannon_entropy,
                    "verdict": hex_data.entropy_verdict,
                    "interpretation": self._interpret_entropy(
                        hex_data.shannon_entropy
                    ),
                },
                "mime_spoofing": {
                    "detected": hex_data.mime_spoof_detected,
                    "details": hex_data.mime_spoof_details,
                },
                "file_format": {
                    "identified_as": hex_data.file_format_identified,
                    "threat_relevance": hex_data.threat_relevance,
                },
                "magic_bytes_extracted": hex_data.magic_bytes_extracted,
                "suspicious_sections_count": hex_data.suspicious_sections_count,
            },
        }

    def _build_ai_section(self, ai_data) -> dict:
        if not ai_data:
            return {"status": "NOT_PERFORMED"}
        return {
            "status": "COMPLETED",
            "analysis_id": ai_data.analysis_id,
            "analyzed_at": ai_data.analyzed_at,
            "model": {
                "name": ai_data.model_name,
                "version": ai_data.model_version,
            },
            "findings": {
                "media_type": ai_data.media_type,
                "verdict": ai_data.verdict,
                "authenticity_score": ai_data.authenticity_score,
                "manipulation_confidence": ai_data.manipulation_confidence,
                "interpretation": self._interpret_ai_verdict(
                    ai_data.verdict,
                    ai_data.manipulation_confidence,
                ),
                "processing_duration_ms": ai_data.processing_duration_ms,
            },
        }

    def _build_custody_section(self, custody_chain) -> list:
        return [
            {
                "sequence": event.event_sequence,
                "event_type": event.event_type,
                "timestamp": event.event_timestamp,
                "actor": {
                    "name": event.actor_name,
                    "badge": event.actor_badge,
                    "role": event.actor_role,
                },
                "description": event.event_description,
                "hash_at_event": event.hash_at_event,
                "hash_verified": event.hash_verified,
                "notes": event.notes,
            }
            for event in custody_chain
        ]

    def _interpret_entropy(self, entropy: float) -> str:
        if entropy >= 7.2:
            return (
                "Critical entropy level. Highly consistent with encrypted, "
                "packed, or obfuscated data."
            )
        elif entropy >= 6.5:
            return (
                "Elevated entropy level. Possible compression or "
                "light obfuscation present."
            )
        else:
            return (
                "Normal entropy level. Consistent with structured "
                "or plain-text data."
            )

    def _interpret_ai_verdict(
        self, verdict: str, manipulation_confidence: float
    ) -> str:
        interpretations = {
            "AUTHENTIC": (
                "AI analysis indicates the media is likely authentic "
                "with no detected manipulation artifacts."
            ),
            "MANIPULATED": (
                f"AI analysis detected manipulation with "
                f"{manipulation_confidence*100:.1f}% confidence. "
                f"Media shows characteristics consistent with "
                f"synthetic generation or editing."
            ),
            "SUSPICIOUS": (
                f"AI analysis flagged suspicious characteristics "
                f"with {manipulation_confidence*100:.1f}% manipulation confidence. "
                f"Further expert review recommended."
            ),
            "INCONCLUSIVE": (
                "AI analysis could not reach a definitive conclusion. "
                "Manual expert review required."
            ),
        }
        return interpretations.get(verdict, "Unknown verdict.")